# LISTA DE LOGS

CREATE TABLE IF NOT EXISTS log_admins (`log_id` INT(11) NOT NULL AUTO_INCREMENT,`Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `Log` VARCHAR(144), PRIMARY KEY (`log_id`))
CREATE TABLE IF NOT EXISTS log_pagos (`log_id` INT(11) NOT NULL AUTO_INCREMENT,`Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `Log` VARCHAR(144), PRIMARY KEY (`log_id`))
CREATE TABLE IF NOT EXISTS log_propiedades (`log_id` INT(11) NOT NULL AUTO_INCREMENT,`Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `Log` VARCHAR(144), PRIMARY KEY (`log_id`))
CREATE TABLE IF NOT EXISTS log_bloqueos (`log_id` INT(11) NOT NULL AUTO_INCREMENT,`Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `Log` VARCHAR(144), PRIMARY KEY (`log_id`))
CREATE TABLE IF NOT EXISTS log_banco (`log_id` INT(11) NOT NULL AUTO_INCREMENT,`Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `Log` VARCHAR(144), PRIMARY KEY (`log_id`))
CREATE TABLE IF NOT EXISTS log_cf (`log_id` INT(11) NOT NULL AUTO_INCREMENT,`Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `Log` VARCHAR(144), PRIMARY KEY (`log_id`))
CREATE TABLE IF NOT EXISTS log_multas (`log_id` INT(11) NOT NULL AUTO_INCREMENT,`Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `Log` VARCHAR(144), PRIMARY KEY (`log_id`))
CREATE TABLE IF NOT EXISTS log_cp (`log_id` INT(11) NOT NULL AUTO_INCREMENT,`Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `Log` VARCHAR(144), PRIMARY KEY (`log_id`))
CREATE TABLE IF NOT EXISTS log_jail (`log_id` INT(11) NOT NULL AUTO_INCREMENT,`Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `Log` VARCHAR(144), PRIMARY KEY (`log_id`))
CREATE TABLE IF NOT EXISTS log_objetos (`log_id` INT(11) NOT NULL AUTO_INCREMENT,`Date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, `Log` VARCHAR(144), PRIMARY KEY (`log_id`))
